#!/usr/bin/env python3
"""Extraiga imágenes preconstruidas y cree otras imágenes."""

import logging
import os
import subprocess
import yaml

_logger = logging.getLogger("andamio-qa")
_logger.setLevel(logging.DEBUG if os.environ["VERBOSE"] == "1"
                 else logging.INFO)
BUILD_FLAGS = os.environ["BUILD_FLAGS"].split()

# Obtener la definición del proyecto
config = subprocess.check_output(["docker-compose", "config"])
_logger.debug("Obtenido docker-compose config:\n%s", config)
config = yaml.safe_load(config)
all_services = config.get("services", {})
services_to_pull = [
    name for (name, service) in all_services.items()
    if "build" not in service
]

# Pull images
_logger.debug("Pulling, tirar imagenes para %s", services_to_pull)
subprocess.check_call(["docker-compose", "pull", *services_to_pull])

# Build images
_logger.debug("Construyendo servicios")
subprocess.check_call(["docker-compose", "build", *BUILD_FLAGS])

# Check odoo bin works
if "odoo" in all_services:
    _logger.debug("Comprobando si el servicio odoo funciona")
    subprocess.check_call([
        "docker-compose", "run", "--rm", "--no-deps",
        "-e", "WAIT_DB=false",
        "-e", "UNACCENT=false",
        "odoo", "--version",
    ])
