#!/usr/bin/env bash
set -e
[ "$VERBOSE" -lt 1 ] || set -x

# Comprobar si complementos existen
errorcode=0
addons="$(addons list -ifxs ' ' $ADDON_CATEGORIES)" || errorcode=$?

# Si no se encuentran complementos, está hecho
[ "$errorcode" -eq 4 ] && exit 0 || [ "$errorcode" -eq 0 ]

# Activar dependencias externas
source /qa/venv/bin/activate
cd /qa
export PATH="$PATH:/qa/mqt/travis"

# Lint
export INCLUDE_LINT="$addons"
test_flake8
